### ISSUE TITLE
404 page when updating to v1.0.0

### ISSUE THREAD

**Issue by bomberstudios** [pravdomil/Fix-Sketch-Trackpad-Speed#4]
The appcast for the v1.0.0 points to https://github.com/pravdomil/fix-sketch-trackpad-speed/releases/download/v1.0.0/FixSketchTrackpadSpeed.sketchplugin.zip, but it looks like there's no 1.0.0 release published, so I'm getting a 404 and no update in Sketch

**Comment by pravdomil** [comment]
closed via https://github.com/pravdomil/Fix-Sketch-Trackpad-Speed/commit/1744b1350355036fa37b4e25b3be341d2ce31e67

**Comment by pravdomil** [comment]
I hope Sketchapp will fix it soon

**Comment by bomberstudios** [comment]
FTR, this has nothing to do with Sketch. You simply didn't create a release for v1.0.0 on GitHub : )

**Comment by pravdomil** [comment]
I hope that Skechapp will fix the trackpad speed soon
